name: Build gh-pages

on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, synchronize]

# GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ministryofjustice/tech-docs-github-pages-publisher:v3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile Markdown to HTML and create artifact
        run: |
          /scripts/deploy.sh

  url-check:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact from build
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          path: github-pages
      - name: Unpack files and check URL links
        run: |
          cd github-pages
          tar -xvf artifact.tar
          npm install linkinator
          npx linkinator . --recurse --markdown \
            --skip https://groups.google.com/* \
            --skip https://github.com/ministryofjustice/dns \
            --skip https://github.com/ministryofjustice/moj-ip-addresses \
            --skip https://github.com/ministryofjustice/mta-sts \
            --skip https://user-guides.operations-engineering.service.justice.gov.uk/images/govuk-large.png \
            --skip https://ministryofjustice.github.io/template-documentation-site/images/govuk-large.png \
            --skip https://operations-engineering.service.justice.gov.uk/images/govuk-large.png \
            --skip https://github.com/ministryofjustice/operations-engineering/issues/* \
          # "URL Check will fail on private and internal GitHub repositories"

